repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: end-of-file-fixer
  - id: forbid-new-submodules

- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21-2
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
